In [11]:
import duckdb
import datasets

ds = datasets.load_dataset('RevolutionCrossroads/si_us_revolutionary_era_collections',
split= 'train'
)

arrow_table = ds.data.table
connection = duckdb.connect()

continental_currency = connection.sql("""
SELECT
title , date, mediaURLs
FROM
  arrow_table
WHERE
  title ILIKE '%CONTINENTAL%'
  AND title ILIKE '%DOLLAR%'
  ORDER BY date
  """)


colonial_currency = connection.sql("""
SELECT
title , date, indexed_places, mediaURLs
FROM
  arrow_table
WHERE
indexed_topics::VARCHAR ILIKE '%NNC COLONIAL CURRENCY%'
AND indexed_topics::VARCHAR NOT ILIKE '%CONTINENTAL%'
ORDER BY date
""")

In [13]:
#display of continental subset
continental_currency.df().head(20)

,title,date,mediaURLs
0,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
1,"1 Continental Dollar, United States, 1776","{""Date made"": ""1776""}",[]
2,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
3,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
4,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
5,"1 Continental Dollar, trial, United States, 1776","{""Date made"": ""1776""}",[]
6,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
7,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
8,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
9,"1 Continental Dollar (copy), United States, 1776","{""Date made"": ""1776""}",[]
10,"1 Continental Dollar, United States, 1776 (copy)","{""Date made"": ""1776""}",[]
11,"1/3 Dollar, Continental Congress, 1774","{""date made"": ""1774""}",[]
12,"2/3 Dollar, Continental Congress, 1774","{""date made"": ""1774""}",[]
13,"1 Dollar, Continental Congress, 1774","{""date made"": ""1774""}",[]
14,"4 Dollars, Continental Congress, 1774","{""date made"": ""1774""}",[]
15,"30 Dollars, Continental Congress, 1775","{""date made"": ""1775"", ""date on object"": ""1775-...",[]
16,"3 Dollars, Continental Congress, 1775","{""date made"": ""1775"", ""date on object"": ""1775-...",[]
17,"3 Dollars, Continental Congress, 1775","{""date made"": ""1775"", ""date on object"": ""1775-...",[]
18,"5 Dollars, Continental Congress, 1775","{""date made"": ""1775"", ""date on object"": ""1775-...",[]
19,"7 Dollars, Continental Congress, 1775","{""date made"": ""1775"", ""date on object"": ""1775-...",[]

In [14]:
#display continental subset
colonial_currency.df().head(20)

,title,date,indexed_places,mediaURLs
0,1 Dollar,"{""Date made"": ""1783""}","[United States, Philadelphia, Pennsylvania]",[]
1,"2 Dollars, Georgia, 1776","{""Date made"": [""1776"", ""1776""]}","[United States, Georgia]",[]
2,"4 Dollars, Georgia, 1776","{""Date made"": [""1776"", ""1776""]}","[United States, Georgia]",[]
3,"6 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[Annapolis, United States, Maryland]",[]
4,"1 Dollar, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
5,"1 Dollar, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[Annapolis, United States, Maryland]",[]
6,"8 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[Annapolis, United States, Maryland]",[]
7,"8 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
8,"6 Dollars, Maryland, 1777","{""date made"": ""1770"", ""date on object"": ""1770-...","[Annapolis, United States, Maryland]",[]
9,"8 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
10,"6 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
11,"4 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
12,"4 Dollars, Maryland, 1767","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
13,"1/6 Dollar, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
14,"1 Dollar, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
15,"2 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
16,"1 Dollar, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
17,"4 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
18,"6 Dollars, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]
19,"1/6 Dollar, Maryland, 1770","{""date made"": ""1770"", ""date on object"": ""1770-...","[United States, Maryland]",[]